## Bag Of Word

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'text':['people watch Netflix','Netflix is watched','people rate movies','Netflix rate movies'],
                   'output':[1,1,0,0]})
df

text  output
0  people watch Netflix       1
1    Netflix is watched       1
2    people rate movies       0
3   Netflix rate movies       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [8]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 7)>

In [5]:
print(cv.vocabulary_)

{'people': 3, 'watch': 5, 'netflix': 2, 'is': 0, 'watched': 6, 'rate': 4, 'movies': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 1 0 1 0]]
[[1 0 1 0 0 0 1]]


In [11]:
cv.transform(['Netflix is a good platform']).toarray()

array([[1, 0, 1, 0, 0, 0, 0]])

*sentiment analysis we can add binary = True*

*max_feature = 1 means we give priority to max output*  

## N-gram

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'netflix': 3, 'people watch': 8, 'watch netflix': 12, 'is': 0, 'watched': 13, 'netflix is': 4, 'is watched': 1, 'rate': 9, 'movies': 2, 'people rate': 7, 'rate movies': 10, 'netflix rate': 5}


In [18]:
print(bow[1].toarray())

[[1 1 0 1 1 0 0 0 0 0 0 0 0 1]]


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(4,4))

more than 4 is giving us error

In [21]:
print(cv.vocabulary_)

AttributeError: 'CountVectorizer' object has no attribute 'vocabulary_'

# TFIDF

In [22]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'text':['people watch Netflix','Netflix is watched','people rate movies','Netflix rate movies'],
                   'output':[1,1,0,0]})
df

text  output
0  people watch Netflix       1
1    Netflix is watched       1
2    people rate movies       0
3   Netflix rate movies       0

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.44809973, 0.55349232, 0.        ,
        0.70203482, 0.        ],
       [0.64450299, 0.        , 0.41137791, 0.        , 0.        ,
        0.        , 0.64450299],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.57735027,
        0.        , 0.        ],
       [0.        , 0.61366674, 0.49681612, 0.        , 0.61366674,
        0.        , 0.        ]])

In [24]:
print(tfidf.idf_)

[1.91629073 1.51082562 1.22314355 1.51082562 1.51082562 1.91629073
 1.91629073]


In [25]:
print(tfidf.get_feature_names_out())

['is' 'movies' 'netflix' 'people' 'rate' 'watch' 'watched']
